# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "backend"

  # for Windows
  #config.vm.box = "bento/ubuntu-24.04"

  # for Mac
  config.vm.box = "net9/ubuntu-24.04-arm64"
  config.vm.box_url = "file:///tmp/net9_ubuntu-24.04-arm64.box"

  config.vm.network "private_network", ip: "10.0.2.102"
end
